version: '3'

services:
  pg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=webapp
  webapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DBNAME=webapp
      - DBPASSWORD=postgrespass
      - DBUSER=postgresuser
      - DBHOST=pg
      - PYTHONBUFFERED=1
    depends_on:
      - pg
      

